language: csharp
dist: trusty
mono: none
dotnet: 2.0

before_script:
- npm install -g serverless

script:
- "./build.sh --quiet verify"
- dotnet test Tests/Tests.csproj

#deploy:
#- provider: script
#  skip_cleanup: true
#  script: "./deploy.sh"
#  on:
#    branch: master
